<?php

declare(strict_types=1);

final class DugaApiClient
{
    public function __construct(private readonly string $appId,private readonly string $agentId,private readonly string $bannerId,private readonly string $endpoint,private readonly string $referer){}

    public function fetchItems(array $params=[]):array
    {
        if(trim($this->appId)===''||trim($this->agentId)==='')throw new RuntimeException('DUGAのアプリケーションIDまたは代理店IDが未設定です。');
        $endpoint=rtrim(trim($this->endpoint),'?');$parts=parse_url($endpoint);
        if(!is_array($parts)||strtolower((string)($parts['scheme']??''))!=='https'||strtolower((string)($parts['host']??''))!=='affapi.duga.jp'||isset($parts['user'])||isset($parts['pass']))throw new RuntimeException('DUGA APIの接続先設定が正しくありません。');
        $query=array_filter(array_merge(['version'=>'1.2','appid'=>$this->appId,'agentid'=>$this->agentId,'bannerid'=>$this->bannerId,'format'=>'json','adult'=>1],$params),static fn(mixed $v):bool=>$v!==null&&$v!=='');
        $url=$endpoint.'?'.http_build_query($query,'','&',PHP_QUERY_RFC3986);$safe=$query;if(isset($safe['appid']))$safe['appid']='***';if(isset($safe['agentid']))$safe['agentid']='***';$safeUrl=$endpoint.'?'.http_build_query($safe,'','&',PHP_QUERY_RFC3986);$hash=hash('sha256',$url);
        $cached=$this->fetchCachedResponse($hash);if($cached!==null)return $cached;
        $lock=$this->acquireRateLimitLock();$ch=curl_init($url);if($ch===false){$this->releaseRateLimitLock($lock);throw new RuntimeException('DUGA API接続の初期化に失敗しました。');}
        $opts=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>30,CURLOPT_FAILONERROR=>false,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_HTTPHEADER=>['Accept: application/json'],CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_PROXY=>''];if(defined('CURLOPT_PROTOCOLS')&&defined('CURLPROTO_HTTPS'))$opts[CURLOPT_PROTOCOLS]=CURLPROTO_HTTPS;
        if(filter_var($this->referer,FILTER_VALIDATE_URL)!==false){$rp=parse_url($this->referer);if(is_array($rp)&&in_array(strtolower((string)($rp['scheme']??'')),['http','https'],true))$opts[CURLOPT_REFERER]=$this->referer;}curl_setopt_array($ch,$opts);
        $response=curl_exec($ch);$this->releaseRateLimitLock($lock);if($response===false){curl_close($ch);$this->insertApiLog('DUGA ItemList',$safeUrl,$hash,0,'{"error":"connection_failed"}',false);throw new RuntimeException('DUGA APIへの接続に失敗しました。');}
        $code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$this->insertApiLog('DUGA ItemList',$safeUrl,$hash,$code,(string)$response,false);if($code>=300)throw new RuntimeException('DUGA APIエラー（HTTP '.$code.'）が発生しました。');$decoded=json_decode((string)$response,true);if(!is_array($decoded))throw new RuntimeException('DUGA APIのJSONを読み取れませんでした。');if(isset($decoded['error']))throw new RuntimeException('DUGA APIからエラーが返されました。');return $decoded;
    }

    private function acquireRateLimitLock(){ $handle=@fopen(sys_get_temp_dir().'/pinkclub-dl-duga-api.lock','c+');if($handle===false||!@flock($handle,LOCK_EX)){if(is_resource($handle))@fclose($handle);usleep(1000000);return null;}rewind($handle);$last=(float)trim((string)stream_get_contents($handle));$wait=(int)ceil((1.0-(microtime(true)-$last))*1000000);if($last>0&&$wait>0)usleep($wait);rewind($handle);ftruncate($handle,0);fwrite($handle,sprintf('%.6F',microtime(true)));fflush($handle);return $handle; }
    private function releaseRateLimitLock($handle):void{if(!is_resource($handle))return;@flock($handle,LOCK_UN);@fclose($handle);}
    private function fetchCachedResponse(string $hash):?array{if(!function_exists('db'))return null;try{$stmt=db()->prepare('SELECT response_body FROM api_logs WHERE request_hash=:request_hash AND response_status=200 AND cache_hit=0 AND created_at>=DATE_SUB(NOW(), INTERVAL 10 MINUTE) ORDER BY id DESC LIMIT 1');$stmt->execute([':request_hash'=>$hash]);$body=$stmt->fetchColumn();if(!is_string($body)||$body==='')return null;$decoded=json_decode($body,true);return is_array($decoded)?$decoded:null;}catch(Throwable){return null;}}
    private function insertApiLog(string $apiName,string $requestUrl,string $requestHash,int $status,string $responseBody,bool $cacheHit):void{if(!function_exists('db'))return;$success=$status>=200&&$status<300;$body=mb_substr($responseBody,0,$success?65535:4096);try{$stmt=db()->prepare('INSERT INTO api_logs (api_name,endpoint,request_params,request_url,request_hash,response_status,status_code,response_body,cache_hit,is_success,message,created_at) VALUES (:api_name,:endpoint,:request_params,:request_url,:request_hash,:response_status,:status_code,:response_body,:cache_hit,:is_success,:message,NOW())');$stmt->execute([':api_name'=>$apiName,':endpoint'=>'search',':request_params'=>json_encode(['url'=>$requestUrl],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':request_url'=>$requestUrl,':request_hash'=>$requestHash,':response_status'=>$status,':status_code'=>$status,':response_body'=>$body,':cache_hit'=>$cacheHit?1:0,':is_success'=>$success?1:0,':message'=>$cacheHit?'cache':($success?'ok':'error')]);return;}catch(Throwable){error_log('duga_api_log status=extended_insert_failed');}try{$stmt=db()->prepare('INSERT INTO api_logs (api_name,request_url,request_hash,response_status,response_body,cache_hit,created_at) VALUES (:api_name,:request_url,:request_hash,:response_status,:response_body,:cache_hit,NOW())');$stmt->execute([':api_name'=>$apiName,':request_url'=>$requestUrl,':request_hash'=>$requestHash,':response_status'=>$status,':response_body'=>$body,':cache_hit'=>$cacheHit?1:0]);}catch(Throwable){error_log('duga_api_log status=legacy_insert_failed');}}
}
