<?php
declare(strict_types=1);
function setup_guard_marker_path(): string{return __DIR__.'/../storage/install/installed.lock';}
function setup_guard_marker_exists(): bool{return is_file(setup_guard_marker_path());}
function setup_guard_mark_installed(): bool{$p=setup_guard_marker_path();$d=dirname($p);if(!is_dir($d)&&!@mkdir($d,0755,true)&&!is_dir($d))return false;try{$s=bin2hex(random_bytes(4));}catch(Throwable){$s=uniqid('',true);}$t=$p.'.tmp-'.$s;if(@file_put_contents($t,"PinkClub installed\n".date('c')."\n",LOCK_EX)===false)return false;@chmod($t,0640);if(!@rename($t,$p)){@unlink($t);return false;}return true;}
function setup_guard_redact_diagnostic_text(string $text): string{foreach(['/\binitial_password=\S+/u'=>'initial_password=[REDACTED]','/\b(?:password|passwd|pass|pwd)=\S+/iu'=>'password=[REDACTED]','/\blocation=\S+:\d+/u'=>'location=[REDACTED]','/\bfailed_sql=.*?(?=\r?\n|$)/u'=>'failed_sql=[REDACTED]','/\bsql=.*?(?=\r?\n|$)/u'=>'sql=[REDACTED]'] as $p=>$r)$text=preg_replace($p,$r,$text)??$text;return $text;}
function setup_guard_sanitize_installer_diagnostics(): void{if(function_exists('installer_log_file_path')){$p=installer_log_file_path();if(is_file($p)&&is_readable($p)&&is_writable($p)){$raw=@file_get_contents($p);if(is_string($raw)){$safe=setup_guard_redact_diagnostic_text($raw);if($safe!==$raw)@file_put_contents($p,$safe,LOCK_EX);}}}if(function_exists('installer_last_error_file_path')){$p=installer_last_error_file_path();if(is_file($p)&&is_readable($p)&&is_writable($p)){$x=json_decode((string)@file_get_contents($p),true);if(is_array($x)){unset($x['file'],$x['line'],$x['failed_sql']);if(isset($x['message']))$x['message']='セットアップ処理に失敗しました。入力内容とサーバー設定を確認してください。';@file_put_contents($p,json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT),LOCK_EX);}}}}
function setup_guard_log_has_completion_evidence(): bool{if(!function_exists('installer_log_file_path'))return false;$p=installer_log_file_path();if(!is_file($p)||!is_readable($p))return false;$raw=@file_get_contents($p);return is_string($raw)&&str_contains(substr($raw,-65536),'step=completed status=ok');}
function setup_guard_db_has_completion_evidence(): bool{try{if(!db_can_connect()||!db_table_exists('admins')||!db_table_exists('settings'))return false;$a=db()->query('SELECT 1 FROM admins ORDER BY id ASC LIMIT 1');if($a===false||$a->fetchColumn()===false)return false;$s=db()->prepare('SELECT setting_value FROM settings WHERE setting_key=:key LIMIT 1');$s->execute([':key'=>'installer.ready']);return (string)($s->fetchColumn()?:'')==='1';}catch(Throwable){return false;}}
function setup_guard_is_known_installed(): bool{if(setup_guard_marker_exists())return true;if(setup_guard_log_has_completion_evidence()||setup_guard_db_has_completion_evidence()){setup_guard_mark_installed();return true;}return false;}
function setup_guard_bootstrap_installed_marker(): void{if(!setup_guard_marker_exists()&&PHP_SAPI!=='cli'&&(setup_guard_log_has_completion_evidence()||setup_guard_db_has_completion_evidence()))setup_guard_mark_installed();}
function setup_guard_recovery_is_authorized(): bool{$u=function_exists('auth_user')?auth_user():null;if(is_array($u)&&(int)($u['id']??0)>0)return true;return function_exists('installer_is_local_request')&&installer_is_local_request();}
function setup_guard_enforce_for_setup_page(): void{if(!headers_sent()){header('Cache-Control: private, no-store, max-age=0');header('Pragma: no-cache');header('X-Robots-Tag: noindex, nofollow',true);}setup_guard_sanitize_installer_diagnostics();ob_start('setup_guard_redact_diagnostic_text');if(setup_guard_is_known_installed()&&!setup_guard_recovery_is_authorized()){if(function_exists('app_redirect'))app_redirect(LOGIN_PATH);header('Location: '.LOGIN_PATH,true,302);exit;}register_shutdown_function(static function():void{setup_guard_sanitize_installer_diagnostics();if(!setup_guard_marker_exists()&&setup_guard_db_has_completion_evidence())setup_guard_mark_installed();});}
